name: Update README from Google Sheets

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 00:00 UTC 跑一次
  workflow_dispatch:      # 也允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with: { python-version: '3.x' }

      - name: Install dependencies
        run: pip install gspread oauth2client

      - name: Set up Google credentials
        run: |
          cat << 'EOF' > service_account.json
${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
EOF

      - name: Debug credentials file
        run: |
          echo "Lines in file: $(wc -l < service_account.json)"
          sed -n '1,3p' service_account.json

      - name: Run update script
        run: python autorun/update_readme.py

      # …后续 Commit & Push 步骤


    - name: Commit & Push changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add README.md
        git commit -m "Update README.md from Google Sheets" || echo "No changes to commit"
        git push
